// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/neyrzx/youmusic/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockTracksInfoGateway is an autogenerated mock type for the TracksInfoGateway type
type MockTracksInfoGateway struct {
	mock.Mock
}

type MockTracksInfoGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracksInfoGateway) EXPECT() *MockTracksInfoGateway_Expecter {
	return &MockTracksInfoGateway_Expecter{mock: &_m.Mock}
}

// Info provides a mock function with given fields: ctx, track
func (_m *MockTracksInfoGateway) Info(ctx context.Context, track entities.TrackInfo) (entities.TrackInfoResult, error) {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 entities.TrackInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TrackInfo) (entities.TrackInfoResult, error)); ok {
		return rf(ctx, track)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.TrackInfo) entities.TrackInfoResult); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Get(0).(entities.TrackInfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.TrackInfo) error); ok {
		r1 = rf(ctx, track)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracksInfoGateway_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockTracksInfoGateway_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - track entities.TrackInfo
func (_e *MockTracksInfoGateway_Expecter) Info(ctx interface{}, track interface{}) *MockTracksInfoGateway_Info_Call {
	return &MockTracksInfoGateway_Info_Call{Call: _e.mock.On("Info", ctx, track)}
}

func (_c *MockTracksInfoGateway_Info_Call) Run(run func(ctx context.Context, track entities.TrackInfo)) *MockTracksInfoGateway_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.TrackInfo))
	})
	return _c
}

func (_c *MockTracksInfoGateway_Info_Call) Return(_a0 entities.TrackInfoResult, _a1 error) *MockTracksInfoGateway_Info_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracksInfoGateway_Info_Call) RunAndReturn(run func(context.Context, entities.TrackInfo) (entities.TrackInfoResult, error)) *MockTracksInfoGateway_Info_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTracksInfoGateway creates a new instance of MockTracksInfoGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracksInfoGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracksInfoGateway {
	mock := &MockTracksInfoGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
