// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/neyrzx/youmusic/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockTracksService is an autogenerated mock type for the TracksService type
type MockTracksService struct {
	mock.Mock
}

type MockTracksService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracksService) EXPECT() *MockTracksService_Expecter {
	return &MockTracksService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, track
func (_m *MockTracksService) Create(ctx context.Context, track entities.TrackCreate) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TrackCreate) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTracksService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTracksService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - track entities.TrackCreate
func (_e *MockTracksService_Expecter) Create(ctx interface{}, track interface{}) *MockTracksService_Create_Call {
	return &MockTracksService_Create_Call{Call: _e.mock.On("Create", ctx, track)}
}

func (_c *MockTracksService_Create_Call) Run(run func(ctx context.Context, track entities.TrackCreate)) *MockTracksService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.TrackCreate))
	})
	return _c
}

func (_c *MockTracksService_Create_Call) Return(_a0 error) *MockTracksService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTracksService_Create_Call) RunAndReturn(run func(context.Context, entities.TrackCreate) error) *MockTracksService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *MockTracksService) GetByID(ctx context.Context, ID int) (entities.Track, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Track, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Track); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(entities.Track)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracksService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTracksService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int
func (_e *MockTracksService_Expecter) GetByID(ctx interface{}, ID interface{}) *MockTracksService_GetByID_Call {
	return &MockTracksService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockTracksService_GetByID_Call) Run(run func(ctx context.Context, ID int)) *MockTracksService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTracksService_GetByID_Call) Return(_a0 entities.Track, _a1 error) *MockTracksService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracksService_GetByID_Call) RunAndReturn(run func(context.Context, int) (entities.Track, error)) *MockTracksService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, filters
func (_m *MockTracksService) GetList(ctx context.Context, filters entities.TrackGetListFilters) ([]entities.Track, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []entities.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TrackGetListFilters) ([]entities.Track, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.TrackGetListFilters) []entities.Track); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.TrackGetListFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracksService_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockTracksService_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - filters entities.TrackGetListFilters
func (_e *MockTracksService_Expecter) GetList(ctx interface{}, filters interface{}) *MockTracksService_GetList_Call {
	return &MockTracksService_GetList_Call{Call: _e.mock.On("GetList", ctx, filters)}
}

func (_c *MockTracksService_GetList_Call) Run(run func(ctx context.Context, filters entities.TrackGetListFilters)) *MockTracksService_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.TrackGetListFilters))
	})
	return _c
}

func (_c *MockTracksService_GetList_Call) Return(_a0 []entities.Track, _a1 error) *MockTracksService_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracksService_GetList_Call) RunAndReturn(run func(context.Context, entities.TrackGetListFilters) ([]entities.Track, error)) *MockTracksService_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTracksService creates a new instance of MockTracksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracksService {
	mock := &MockTracksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
