basePath: /api/v1
definitions:
  v1.HTTPError:
    properties:
      message:
        type: string
    type: object
  v1.TrackLyricResponse:
    properties:
      orderID:
        type: integer
      verse:
        type: string
    type: object
  v1.TrackUpdateRequest:
    properties:
      artist:
        type: string
      link:
        example: https://y.be/asd2d2cW
        format: uri
        type: string
      lyric:
        example: |-
          verse #1

          verse #2

          verse #3
        type: string
      released:
        example: 10.10.2010
        format: date
        type: string
      track:
        type: string
    type: object
  v1.TracksCreateRequest:
    properties:
      group:
        example: Muse
        type: string
      song:
        example: Song name
        type: string
    required:
    - group
    - song
    type: object
  v1.TracksResponse:
    properties:
      artist:
        type: string
      link:
        type: string
      lyric:
        items:
          type: string
        type: array
      released:
        type: string
      track:
        type: string
      trackID:
        type: integer
    type: object
  v1.TracksRetrieveResponse:
    properties:
      artist:
        type: string
      link:
        type: string
      lyric:
        items:
          type: string
        type: array
      released:
        type: string
      track:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: khorev.valeriy@yandex.ru
    name: API Support
  description: Это проект был разработан в рамках тестового задания от EffectiveMobile
  license:
    name: MIT
    url: https://github.com/Neyrzx/YouMusic?tab=MIT-1-ov-file
  termsOfService: http://swagger.io/terms/
  title: YouMusic
  version: 0.0.1
paths:
  /tracks/:
    get:
      consumes:
      - application/json
      description: List of tracks with filters
      parameters:
      - description: Limit result.
        in: query
        name: limit
        type: string
      - description: Offset result.
        in: query
        name: offset
        type: string
      - description: Name of the artist or group.
        in: query
        name: artist
        type: string
      - description: Title of track.
        in: query
        name: track
        type: string
      - description: List of tracks.
        in: query
        name: releasedyear
        type: string
      - description: Exact link
        in: query
        name: link
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            items:
              $ref: '#/definitions/v1.TracksResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: List of tracks
      tags:
      - Tracks
    post:
      consumes:
      - application/json
      description: Creating track
      parameters:
      - description: Create track by song and group names.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.TracksCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success created
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: Create track
      tags:
      - Tracks
  /tracks/{id}/:
    delete:
      consumes:
      - application/json
      description: Deliting track by track id
      parameters:
      - description: track id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: Delete track
      tags:
      - Tracks
    get:
      consumes:
      - application/json
      description: Retriving track
      parameters:
      - description: track id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: get track result
          schema:
            $ref: '#/definitions/v1.TracksRetrieveResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "422":
          description: Validation errors
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: Retrive track
      tags:
      - Tracks
    patch:
      consumes:
      - application/json
      description: Updating the track
      parameters:
      - description: track id
        in: path
        name: id
        required: true
        type: integer
      - description: track id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.TrackUpdateRequest'
      produces:
      - application/json
      responses:
        "204":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: Update the tracks
      tags:
      - Tracks
  /tracks/{id}/lyric/:
    get:
      consumes:
      - application/json
      description: Retrive lyric verse with offset
      parameters:
      - description: track id
        in: path
        name: id
        required: true
        type: integer
      - description: verse offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/v1.TrackLyricResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "422":
          description: Validation errors
          schema:
            $ref: '#/definitions/v1.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.HTTPError'
      summary: Retrive verse
      tags:
      - Tracks
swagger: "2.0"
